title: Theology and Tech
description: Theology writing shaped by careful thinking and technical workflow
remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-remote-theme
- jekyll-include-cache
minimal_mistakes_skin: default
markdown: kramdown
